[FEATURE] Migrate Querybuilder->execute()
sabbelasichon/typo3-rector pull request #3068
Opened 2022-07-07 21:08 UTC by helsner

Resolves: #2938

2022-07-07 21:30 UTC, simonschaufi requested changes

2022-07-07 21:30 UTC, simonschaufi commented on tests/Rector/v12/v0/typo3/MigrateQueryBuilderExecuteRector/Fixture/fixture.php.inc
> +use TYPO3\CMS\Core\Database\ConnectionPool;
empty line after namespace

2022-07-07 21:30 UTC, simonschaufi commented on tests/Rector/v12/v0/typo3/MigrateQueryBuilderExecuteRector/Fixture/fixture.php.inc
> +
only one empty line

2022-07-07 21:30 UTC, simonschaufi commented on tests/Rector/v12/v0/typo3/MigrateQueryBuilderExecuteRector/Fixture/fixture.php.inc
> +
only one empty line

2022-07-07 21:30 UTC, simonschaufi commented on composer.json
> +            "cweagans/composer-patches": true,
why are they added? We don't use them any more.

2022-07-08 06:30 UTC, helsner commented
We got an issue with the last test i added.
Sometimes the query is build with conditions etc. in between, so the chain does not happen directly, but is split into multiple pieces, with only the execute() at the end.
Either we leave this, then i'll adapt the test or we can fix it.
At least i prevented it from being falsely refactored

2022-07-08 06:30 UTC, helsner commented
I will take care of the phpstan stuff when the actual rule is done.

2022-07-14 17:46 UTC, helsner commented on tests/Rector/v12/v0/typo3/MigrateQueryBuilderExecuteRector/Fixture/fixture.php.inc
> +$result = $testSecond
i talked to Tomas, this is pretty pretty hard and would only work with assumptions.
I will provide a hint functionality as we can identify the cases but not migrate them.

2022-07-14 18:21 UTC, merged